### ISSUE TITLE
crates.io packages broken on Windows

### ISSUE THREAD

**Issue by Eljay** [Geal/nom#117]
Output:
```
Unable to get packages from source

Caused by:
  Failed to unpack package `nom v1.0.0-beta`

Caused by:
  The filename, directory name, or volume label syntax is incorrect. (os error 123)
```

This seems to be due to Cargo blindly packaging all files in the crate directory, and there being a file called `:w` in the root which is an invalid filename on Windows.

**Comment by kroltan** [comment]
I'm having this error too.
Windows 10, Rust 1.4 x64 (1.2 also broken).

**Comment by Geal** [comment]
I'm releasing a new crate this afternoon or tomorrow to fix that. Thanks for the report!

**Comment by Geal** [comment]
The [1.0.0-beta2](https://crates.io/crates/nom/1.0.0-beta2) should fix this. Please let me know if that is alright with you.

Also, if you have feedback on the 1.0 features (and bugs), I'm interested :)

**Comment by kroltan** [comment]
@Geal Still broken. Now it is able to download, but compilation fails:

```
E:\Projects\vdf\src>cargo test --verbose
   Compiling nom v1.0.0-beta2
     Running `rustc C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\lib.rs --crate-name nom --crate-type lib -g --cfg "feature=\"stream\"" --cfg "feature=\"default\"" -C metadata=08dcc5582a591963 -C extra-filename=-08dcc5582a591963 --out-dir E:\Projects\vdf\target\debug\deps --emit=dep-info,link -L dependency=E:\Projects\vdf\target\debug\deps -L dependency=E:\Projects\vdf\target\debug\deps -Awarnings`
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:44: 74:64 error: the parameter type `E` may not live long enough [E0309]
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74     if let &ConsumerState::Done(_,ref o) = self.apply(consumer) {
                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~
note: in expansion of if let expansion
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:5: 78:6 note: expansion site
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:44: 74:64 help: run `rustc --explain E0309` to see a detailed explanation
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:44: 74:64 help: consider adding an explicit lifetime bound `E: 'b`...
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:44: 74:64 note: ...so that the reference type `&stream::ConsumerState<O, E, M>` does not outlive the data it points at
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74     if let &ConsumerState::Done(_,ref o) = self.apply(consumer) {
                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~
note: in expansion of if let expansion
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:5: 78:6 note: expansion site
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:44: 74:64 error: the parameter type `M` may not live long enough [E0309]
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74     if let &ConsumerState::Done(_,ref o) = self.apply(consumer) {
                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~
note: in expansion of if let expansion
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:5: 78:6 note: expansion site
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:44: 74:64 help: run `rustc --explain E0309` to see a detailed explanation
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:44: 74:64 help: consider adding an explicit lifetime bound `M: 'b`...
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:44: 74:64 note: ...so that the reference type `&stream::ConsumerState<O, E, M>` does not outlive the data it points at
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74     if let &ConsumerState::Done(_,ref o) = self.apply(consumer) {
                                                                                                                                           ^~~~~~~~~~~~~~~~~~~~
note: in expansion of if let expansion
C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\stream.rs:74:5: 78:6 note: expansion site
error: aborting due to 2 previous errors
Could not compile `nom`.

Caused by:
  Process didn't exit successfully: `rustc C:\Users\kroltan\.cargo\registry\src\github.com-0a35038f75765ae4\nom-1.0.0-beta2\src\lib.rs --crate-name nom --crate-type lib -g --cfg feature="stream" --cfg feature="default" -C metadata=08dcc5582a591963 -C extra-filename=-08dcc5582a591963 --out-dir E:\Projects\vdf\target\debug\deps --emit=dep-info,link -L dependency=E:\Projects\vdf\target\debug\deps -L dependency=E:\Projects\vdf\target\debug\deps -Awarnings` (exit code: 101)
```

Should this be a new issue?

**Comment by Geal** [comment]
Which version of Rust are you using? nom 1.0 works with the latest stable. If you want to keep an older Rust, you can just deactivate the streaming facilities (producers and consumers) like this:

```toml
[dependencies.nom]
version = "1.0.0-beta2"
default-features = false
```

**Comment by kroltan** [comment]
@Geal Oh, this was a problem with my Rust setup. I had 1.2.0 on my PATH, updated and added 1.4.0 to the PATH, but forgot to remove the old one from the PATH. False alarm :)

**Comment by Geal** [comment]
I'm writing a doc for the upgrade path to 1.0 (since I willingly broke a lot of things). If you see other issues, please ping me :)

**Comment by kroltan** [comment]
Sir yes sir!
